<div class="box">
    <form action="" method="POST" id="formPerson<?=$this->role?>" style="float: left;">
        <table>
            <tr>
                <td>
                    Логин
                </td>
                <td>
                    <input type="text" name="login" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    Пароль
                </td>
                <td>
                    <input type="text" name="password" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    Имя
                </td>
                <td>
                    <input type="text" name="name" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    Фамилия
                </td>
                <td>
                    <input type="text" name="sname" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    Отчество
                </td>
                <td>
                    <input type="text" name="lname" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    Категория
                </td>
                <td>
                    <select name="category">
                        <option value="1">МСМК</optoin>
                        <option value="2">МС</optoin>
                        <option value="3">КМС</optoin>
                        <option value="4">| Ю</optoin>
                        <option value="5">|| Ю</optoin>
                        <option value="6">||| Ю</optoin>
                        <option value="7">|</optoin>
                        <option value="8">||</optoin>
                        <option value="9">|||</optoin>
                        <option value="9">ЮСС</optoin>
                        <option value="9">СС|||</optoin>
                        <option value="9">CC||</optoin>
                        <option value="9">CC|</optoin>
                        <option value="9">CCBK</optoin>
                    </select><br />
                </td>
            </tr>
            <tr>
                <td>
                    Паспорт
                </td>
                <td>
                    <input type="text" name="passport" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    Дата рождения
                </td>
                <td>
                    <input type="text" name="borndate" /><br />
                </td>
            </tr>
        </table>
        <input type="hidden" name="role" value="<?=$this->role?>" />        
        <input type="hidden" name="type" value="<?=BusinessLogic::AJAX_PERSON_ACTION?>" />        
        <input type="button" id="submitPerson<?=$this->role?>" value="Добавить" />        
    </form>
    <div id="error_box<?=$this->role?>" style="float: left;color: red;"></div>
</div>
<script type="text/javascript">
$(document).ready(function()
{
    $("#submitPerson<?=$this->role?>").on("click", function()
    {
        var post = $("#formPerson<?=$this->role?>").serialize();
        $.ajax({
            url: '?action=ajax',
            type: 'post',
            data: post,
            dataType: 'json',
            success: function(data)
            {
                if(data.status == 'success')
                    window.location.reload();
                else
                    $('#error_box<?=$this->role?>').html(data.message);
            },
            error: function(data)
            {
                console.log(data);
            }
        });
    });
})
</script>
<div class="clear"></div>
<br>
<br>