<div class="athlete">
    <div class="personal-card">
        <form class="form-horizontal" action="sign-up" method="post">
            <?php echo $this->partial('information-card', $this); ?>
            <div class="control-group">
                <label class="control-label" for="inputLogin">Спортивный разряд</label>
                <div class="controls">
                    <input type="text" class="inputSportRank" placeholder="Спортивный разряд">
                </div>
            </div>
        </form>
    </div>

    
</div>