<!--Спортивные категории-->
<div class="categories">
    <table class="table table-striped">
        <tr>
            <td>Дисциплина</td>
            <td>Время</td>
            <td>МСМК</td>
            <td>МС</td>
            <td>КМС</td>
            <td>I</td>
            <td>II</td>
            <td>III</td>
            <td>I ю.</td>
            <td>II ю.</td>
            <td>III ю.</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>