<div class="tabs">
        <div id="<?=$item['id']?>">
            <div class="sheet_head" style="width: 50px;">
                &nbsp;
            </div>
            <div class="sheet_head" style="width: 200px;">
                Название
            </div>
            <div class="sheet_head">
                Дата открытия
            </div>
            <div class="sheet_head">
                Страна
            </div>
            <div class="sheet_head">
                Город
            </div>
            <div class="sheet_head">
                Место проведения
            </div>
            <div class="sheet_head">
                Дата закрытия
            </div>
        </div>
    
    <?php foreach($this->events as $item): ?>
        <div id="<?=$item['id']?>" class="row" rel="event">
            <div class="sheet_edit" style="width: 50px;"><a class="edit_row">[ред]</a><a class="save_row" rel="<?=$item['role_id']?>" style="display: none;">[сох]</a></div>
            <div class="sheet" rel="name" style="width: 200px;"><?=$item['name']?></div>
            <div class="sheet" rel="event_date"><?=implode('-', array_reverse(explode('-', $item['event_date'])))?></div>
            <div class="sheet" rel="country"><?=$item['country']?></div>
            <div class="sheet" rel="city"><?=$item['city']?></div>
            <div class="sheet" rel="address"><?=$item['address']?></div>
            <div class="sheet" rel="close_date"><?=implode('-', array_reverse(explode('-', $item['close_date'])))?></div>
        </div>
    <?php endforeach; ?>
</div>