<div class="information-card">
    <?php
    //запрос к бд
    $info = array(
        'name' => "name",
        'sname' => "sname",
        'lname' => "lname",
        'sex' => "sex",
        'email' => "email",
        'borndate' => "borndate",
        'tin' => "tin",
        'passport' => "passport",
        'login' => "login"
    );
    ?>
    <label class="control-label" id="user-info"><?php echo $info['name']?></label>
    <label class="control-label" id="user-info"><?php echo $info['sname']?></label>
    <label class="control-label" id="user-info"><?php echo $info['lname']?></label>
    <label class="control-label" id="user-info"><?php echo $info['sex']?></label>
    <label class="control-label" id="user-info"><?php echo $info['email']?></label>
    <label class="control-label" id="user-info"><?php echo $info['borndate']?></label>
    <label class="control-label" id="user-info"><?php echo $info['tin']?></label>
    <label class="control-label" id="user-info"><?php echo $info['passport']?></label>
    <label class="control-label" id="user-info"><?php echo $info['login']?></label>
</div>