<div class="information-card">
    <?php
    //запрос к бд
    $id = DBunit::getId($_POST["login"], $_POST["password"]);
    $info = DBunit::getUserInfo($id);
    ?>
    <label class="control-label" id="user-info">Имя: <?php echo $info['name']?></label>
    <label class="control-label" id="user-info">Фамилия: <?php echo $info['sname']?></label>
    <label class="control-label" id="user-info">Отчество: <?php echo $info['lname']?></label>
    <label class="control-label" id="user-info">E-mail: <?php echo $info['email']?></label>
    <label class="control-label" id="user-info">Дата рождения: <?php echo $info['borndate']?></label>
    <label class="control-label" id="user-info">ИНН: <?php echo $info['tin']?></label>
    <label class="control-label" id="user-info">Паспорт: <?php echo $info['passport']?></label>
    <label class="control-label" id="user-info">Логин: <?php echo $info['login']?></label>
</div>