<div id="my-athletes-shell">
    <div class="form-pos-up-part">
        <div class="form-title">
            <span>Мои спортсмены</span>
        </div>
        <div class="form-line"></div>
        <div class="form-btns-pos">
            <button class="form-btn-up" onClick="" name=""></button>
        </div>
        <div class="form-line-up"></div>
    </div>
    <div class="coach-scroll-box scroll-simple">
        <div class="athletes-info">
            <div class="photo-min"></div>
            <div class="ath-info">
                <div>Попова Татьяна Семеновна</div>
                <div>18.12.1995 г.р.</div>
                <div>Звание/Разряд: МС</div>
            </div>
        </div>
        <div class="clr"></div>
        <div class="athletes-info">
            <div class="photo-min"></div>
            <div class="ath-info">
                <div>Попова Татьяна Семеновна</div>
                <div>18.12.1995 г.р.</div>
                <div>Звание/Разряд: МС</div>
            </div>
        </div>
    </div>
    <div class="form-pos-down-part">
        <div class="form-line-down"></div>
        <div class="form-btns-pos">
            <button class="form-btn-down" onClick="" name=""></button>
        </div>
    </div>
</div>