<!--<div id="set-workout">
    <form class="form-horizontal" role="form" >
        <div class="form-group">
            <label for="inputDate" class="col-sm-2 control-label">Дата</label>
            <div class="col-sm-10">
                <input type="text" class="form-control workoutInput" id="inputDate" placeholder="Дата тренировки">
            </div>
        </div>
        <div class="form-group">
            <label for="inputWork" class="col-sm-2 control-label">Работа</label>
            <div class="col-sm-10">
                <input type="text" class="form-control  workoutInput" id="inputWork" placeholder="Выполненная работа">
            </div>
        </div>
        <div class="form-group">
            <label for="inputResult" class="col-sm-2 control-label">Результат</label>
            <div class="col-sm-10">
                <input type="text" class="form-control  workoutInput" id="inputResult" placeholder="Результаты">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <a type="success" class="btn btn-primary" id="button-set-workout" onclick="setWorkout();">Записать тренировку</a>
            </div>
        </div>
    </form>
</div>
-->
<div id="set-workout">
    <form class="form-horizontal" role="form" >
        <div id="rec-workout-shell">
            <div class="form-pos-up-part">
                <div class="form-title">
                    <span>Записать тренеровку</span>
                </div>
            </div>
            <div class="scroll-box scroll-simple">
                <div id="rec-workout-left">
                    <div id="rec-workout-text-data">Дата:</div>
                    <div id="calendar-shell">
                        <div id="calendar"></div>
                        <input type="text" id="inputDate" placeholder="Дата тренировки">
                    </div>
                </div>
                <div id="rec-workout-right">
                    <label class="label-checkbox-align">сегодня <input type="checkbox"></label>
                </div>
                <div class="clr"></div>
                <div id="rec-workout-left2">
                    <div id="rec-workout-text-work">Работа:</div>
                    <div class="clr"></div>
                    <div id="rec-workout-text-result">Результат:</div>
                </div>
                <div id="rec-workout-right2">
                    <input type="text" class="rec-workout-input" id="inputWork">
                    <div class="clr"></div>
                    <input type="text" class="rec-workout-input" id="inputResult">
                </div>
                <div class="clr"></div>
                <a type="success" class="btn-2" id="rec-workout-ok-btn" onclick="setWorkout();">OK</a>
                <div class="clr"></div>
            </div>
        </div>
    </form>
</div>