<div id="set-workout">
    <form class="form-horizontal" role="form">
        <div class="form-group">
            <label for="inputDate" class="col-sm-2 control-label">Дата</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputDate" placeholder="Дата тренировки">
            </div>
        </div>
        <div class="form-group">
            <label for="inputWork" class="col-sm-2 control-label">Работа</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputWork" placeholder="Выполненная работа">
            </div>
        </div>
        <div class="form-group">
            <label for="inputResult" class="col-sm-2 control-label">Результат</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputResult" placeholder="Результаты">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="button" class="btn btn-primary" id="button-set-workout" onclick="setWorkout();">Записать тренировку</button>
            </div>
        </div>
    </form>
</div>
