<div id="set-workout-plan">
    <form class="form-horizontal" role="form">
        <div id="day">
            <div class="form-group">
                <label for="inputDate" class="col-sm-2 control-label">День</label>
                <div class="col-sm-10">
                    <select class="form-control" id="workout-day" placeholder="День недели">
                        <option>ПН</option>
                        <option>ВТ</option>
                        <option>СР</option>
                        <option>ЧТ</option>
                        <option>ПТ</option>
                        <option>СБ</option>
                        <option>ВС</option>
                    </select>
                </div>

            </div>
            <div class="form-group">
                <label for="inputWork" class="col-sm-2 control-label">Работа</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputWork" placeholder="Выполненная работа">
                </div>
            </div>
            <div class="form-group">
                <label for="inputResult" class="col-sm-2 control-label">Результат</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputResult" placeholder="Результаты">
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="button" class="btn btn-primary" id="button-add-workout-plan" onclick="addNewDay();">Добавить день</button>
                <button type="button" class="btn btn-primary" id="button-set-workout-plan" onclick="setWorkoutPlan();">Записать план тренировок</button>
            </div>
        </div>
    </form>
</div>
