<div id="upcoming-contest-shell">
    <div class="form-pos-up-part">
        <div class="form-title">
            <span>Предстоящие соревнования</span>
        </div>
        <div class="form-line"></div>
        <div class="form-btns-pos">
            <button class="form-btn-up" onClick="" name=""></button>
        </div>
        <div class="form-line-up"></div>
    </div>
    <div class="scroll-box scroll-simple">
        <div class="table-1">
            <?php
            $events = DBunit::getNextEvents();
            $res = "<table" . " id='sporting-events'" . ">
                    <tr><td><a href=\"\">Дата</td>
                    <td><a href=\"\">Наименование</td>
                    <td></td></tr>";
            for ($i = 0; $i < count($events); $i++)
            {
                $res = $res . "<tr>"
                    . "<td>" . $events[$i]['event_date']    . "</td>"
                    . "<td>" . $events[$i]['name']          . "</td>"
                    . "<td>" . "<button type=\"button\" class=\"btn-1\" id=\"button-send-claim-" . $events[$i]['id'] . "\" event-id=\""
                    . $events[$i]['id'] . "\"onclick=\"sendClaim(this);\" >Подать заявку</button>"
                    . "<button type=\"button\" class=\"btn-1 cancel-claim\" id=\"button-cancel-claim-" . $events[$i]['id'] . "\" event-id=\""
                    . $events[$i]['id'] . "\"onclick=\"cancelClaim(this);\" >Отменить заявку</button>"
                    . "</td>"
                    . "</tr>";
            }
            $table = $res . "</table>";
            echo  $table;
            ?>
        </div>
    </div>
    <div class="form-pos-down-part">
        <div class="form-line-down"></div>
        <div class="form-btns-pos">
            <button class="form-btn-down" onClick="" name=""></button>
        </div>
    </div>
</div>

