<div id="statistics-shell">
    <div class="form-pos-up-part">
        <div class="form-title">
            <span>Статистика</span>
        </div>
        <div class="form-line"></div>
        <div class="form-btns-pos">
            <button class="form-btn-up" onClick="" name=""></button>
        </div>
        <div class="form-line-up"></div>
    </div>
    <div class="scroll-box-statistics scroll-simple">
        <div class="table-1">
            <table>
                <tr>
                    <td><a href="">Дата</td>
                    <td><a href="">Дисциплина</td>
                    <td><a href="">Результат</td>
                </tr>
                <tr>
                    <td>25.12.2013</td>
                    <td>Бег 100 м</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>25.12.2013</td>
                    <td>Бег 100 м</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>25.12.2013</td>
                    <td>Бег 100 м</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>25.12.2013</td>
                    <td>Бег 100 м</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>25.12.2013</td>
                    <td>Бег 100 м</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>25.12.2013</td>
                    <td>Бег 100 м</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>25.12.2013</td>
                    <td>Бег 100 м</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
                <tr>
                    <td>26.12.2013</td>
                    <td>Спортивная ходьба</td>
                    <td>2.00.04</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="form-pos-down-part">
        <div class="form-line-down"></div>
        <div class="form-btns-pos">
            <button class="form-btn-down" onClick="" name=""></button>
        </div>
    </div>
</div>