<div id="training-plan-shell">
    <div class="form-pos-up-part">
        <div class="form-title">
            <span>Последние планы тренировок</span>
        </div>
        <div class="form-line"></div>
        <div class="form-btns-pos">
            <button class="form-btn-up" onClick="" name=""></button>
        </div>
        <div class="form-line-up"></div>
    </div>
    <div class="scroll-box-2 scroll-simple">
        <?php
            $coach_id = mysql_real_escape_string($_SESSION['id']);;
            $workout_plans = DBunit::getWeekPlans($coach_id);
            $result = "";
            for ($j = 0; $j < count($workout_plans); $j++)
            {
                $workout_plan = $workout_plans[$j];
                $res = "";
                for ($i = 0; $i < count($workout_plan); $i++)
                {
                    if ($i == 0)
                    {
                        $res = $res . "<span id='week-begin-date'>" . $workout_plan[$i]['week_begin_date'] . "</span>"
                            . "<span id='separator'>-</span>"
                            . "<span id='week-end-date'>"   . $workout_plan[$i]['week_end_date']   . "</span>"
                            . "<span id='week-comments'>"   . $workout_plan[$i]['comments']
                            . "</span><div class=\"clr\"></div>"
                            . "<div class=\"table-2\"><table id='week'>";
                    }
                    $res = $res . "<tr id='day'>"
                        . "<td id='name'>"   . $workout_plan[$i]['week_day']     . "</td>"
                        . "<td>Работа:</td><td id='work'>"   . $workout_plan[$i]['work']         . "</td>"
                        . "<td>Результат:</td><td id='result'>" . $workout_plan[$i]['result']       . "</td>"
                        . "</tr>";
                }
                $res = $res . "</table></div>";
                $result = $result . $res;
            }
            echo  $result;
        ?>
    </div>
    <div class="form-pos-down-part">
        <div class="form-line-down"></div>
        <div class="form-btns-pos">
            <button class="form-btn-down" onClick="" name=""></button>
        </div>
    </div>
</div>