<div id="workout-plan">
    <?php
    $workout_plan = DBunit::getWeekPlan();
    $res = "<div" . " id='week'" . ">";

    for ($i = 0; $i < count($workout_plan); $i++)
    {
        if ($i == 0)
        {
            $res = $res . "<span id='week-begin-date'>" . $workout_plan[$i]['week_begin_date'] . "</span>"
                        . "<span id='week-end-date'>" . $workout_plan[$i]['week_end_date'] . "</span>"
                        . "<span id='week-comments'>" . $workout_plan[$i]['comments'] . "</span>";
        }
        $res = $res . "<day>"
            . "<span id='name'>" . $workout_plan[$i]['week_day']     . "</a>"
            . "<span>" . $workout_plan[$i]['work']         . "</span>"
            . "<span>" . $workout_plan[$i]['result']   . "</span>"
            . "</day>";
    }
    $res = $res . "</div>";
    echo  $res;

    ?>
</div>
