<div id="workouts">
    <?php
    $id = mysql_real_escape_string($_SESSION['id']);
    $workouts = DBunit::getAllWorkouts($id);
    $res = "<table" . " id='workouts'" . ">";
    for ($i = 0; $i < count($workouts); $i++)
    {
        $res = $res . "<tr>"
            . "<td>" . $workouts[$i]['id']     . "</td>"
            . "<td>" . $workouts[$i]['date']   . "</td>"
            . "<td>" . $workouts[$i]['work']   . "</td>"
            . "<td>" . $workouts[$i]['result'] . "</td>"
            . "</tr>";
    }

    $table = $res . "</table>";


    echo  $table;

    ?>
</div>
