<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 4.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
    <head runat="server" profile="http://gmpg.org/xfn/11">
        <title>admin</title>
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <script type="text/javascript" src="/js/jquery-1.8.2.min.js"></script>
		<script type="text/javascript" src="/js/bootstrap.js"></script>
        <script type="text/javascript" src="/js/md5.js"></script>
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>
    <body>
    <?php //echo $this->contentadmin(); ?>
    </body>
</html>