<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html
    xmlns="http://www.w3.org/1999/xhtml"
    xml:lang="ru"
    lang="ru">
<head runat="server" profile="http://gmpg.org/xfn/11">
    <title>Лёгкая атлетика</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link href="img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
    <link href="img/favicon.ico" rel="icon" type="image/x-icon"/>
    <link rel="stylesheet" href="css/style.css"/>
    <script src="js/jquery-1.7.2.js" type="text/javascript"></script>
    <script src="js/script.js" type="text/javascript"></script>

    <script type="text/javascript" src="/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.js"></script>
    <script type="text/javascript" src="/js/app.js"></script>
    <script type="text/javascript" src="/js/black.js"></script>
    <script src="js/jquery.leanModal.min.js" type="text/javascript"></script>
    <script>
        $(function() {
            $('a[rel*=leanModal]').leanModal({ top : 200 });
        });
    </script>
</head>
<body onload="myOnLoad();">
    <script type="text/javascript">
        $(function(){
           if($("#tabs").length)
             $( "#tabs" ).tabs();
        });
    </script>
    <?php echo $this->content(); ?>
</body>
</html>
