<?php echo $this->partial('header', $this); ?>
<script type="text/javascript" src="/js/jquery.tabify.source.js"></script>
<script>
$(document).ready(function()
{
    $("#admin-menu-shell").tabify(function(){});
});
</script>

    
    
    
			<div id="admin-menu-shell">
				<ul id="admin-menu">
					<li class="admin-menu-btn" name=""><a href="#sportsmens">Спортсмены</a></li>
					<div id="admin-menu-sepor"></div>
					<li class="admin-menu-btn" name=""><a href="#treners">Тренеры</a></li>
					<div id="admin-menu-sepor"></div>
					<li class="admin-menu-btn" name=""><a href="#events">Тренеровки</a></li>
				</ul>
			</div>	
    
    
    
    
    <div id="sportsmens" class="tab_block">
        <?php echo $this->partial('addingPersonForm', array('role' => BusinessLogic::ROLE_SPORTSMEN)); ?>
        <?php echo $this->partial('personsList', array('items' => $this->sportsmens)); ?>
    </div>
    <div id="treners" class="tab_block">
        <?php echo $this->partial('addingPersonForm', array('role' => BusinessLogic::ROLE_TRENER)); ?>
        <?php echo $this->partial('personsList', array('items' => $this->treners)); ?>
    </div>
    <div id="events" class="tab_block">
        <?php echo $this->partial('addingEventForm', $this); ?>
        <?php echo $this->partial('eventsList', $this); ?>
    </div>
</div>

<?php echo $this->partial('footer', $this); ?>