<?php
echo $this->partial('header', $this);
//echo "логин=" . $_POST["login"] . "пароль=" . $_POST["password"];
if (DBunit::checkLoginPassword($_POST["login"], $_POST["password"]))
{
    //забираем себе его id
    $id = DBunit::getId($_POST["login"], $_POST["password"]);
    switch(DBunit::getRoleById($id))
    {
        //администратор
        case 1:{
            echo "Зашли как администратор";
        }
            break;
        //спортсмен
        case 2:{
            echo "Зашли как спортсмен";
            //форма записи тренировок
            echo $this->partial('set-workout', $this);
            //личные данные
            echo $this->partial('information-card', $this);
            //последние тренировки
            echo $this->partial('workouts', $this);
            //статистика
            //echo $this->partial('statistic', $this);

            //предстоящие соревнования
            //план тренировок
        }
            break;
        //тренер
        case 3:{
            echo "Зашли как тренер";
            //форма записи планов тренировок
            //последние планы тренировок
            //личные данные
            echo $this->partial('information-card', $this);
            //предстоящие соревнования
        }
            break;
    }
    //echo $this->partial('workouts', $this);

    //echo $this->partial('statistic', $this);

    //тут будет выбор между ролями
    //echo $this->partial('athlete', $this);

    //echo $this->partial('coach', $this);
}
else{
    echo "Такого пользователя в системе нет";
    //header("HTTP/1.0 404 Такого пользователя в системе нет.");
}
/*
//если пользователь не менял пароль
if ($_POST["newPassword"] == "")
{
    DBunit::updateUserWithoutPassword($user_id, $_POST["name"], $_POST["sName"], $_POST["lName"], $_POST["borndate"], $_POST["tin"], $_POST["passport"], $_POST["login"]);
    echo "Информация обновлена";
}
//решил поменять и пароль
else if (DBunit::getPassword($_POST["login"]) != $_POST["newPassword"])
{
    if ($_POST["newPassword"] == $_POST["repeatNewPassword"])
    {
        DBunit::updateUser($user_id, $_POST["name"], $_POST["sName"], $_POST["lName"], $_POST["borndate"], $_POST["tin"], $_POST["passport"], $_POST["login"], $_POST["password"]);
        echo "Информация обновлена";
    }
    else
    {
        echo "Пароли не совпадают!";
    }
}
//<div class="body">
//</div>
*/

echo $this->partial('footer', $this); ?>