<?php

echo $this->partial('header', $this);
if (DBunit::checkLogin($_POST["login"]))
{
    echo "Пользователь с таким логином уже зарегистрирован. Извините, Вам придется придумать себе новый логин.";
    echo $this->partial('sign-up', $this);
}
else
{
    $role = 0;
    if ($_POST["role"] == "Спортсмен")
        $role = 2;
    else if ($_POST["role"] == "Тренер")
        $role = 3;
    DBunit::ConnectToDB();
    DBunit::createUser($_POST["name"], $_POST["sName"], $_POST["lName"], $_POST["email"], 15, $_POST["borndate"], $_POST["tin"], $_POST["passport"], $role, $_POST["login"], $_POST["newPassword"]);
echo "Вы успешно зарегистрированы";
}
echo $this->partial('footer', $this); ?>


