<?php
    echo $this->partial('header', $this);
    echo $this->partial('panelRole', $this);
?>
<div id="main">
    <?php
        echo $this->partial('search', $this);
    ?>
    <div id="info-shell">
        <div id="info-left">
            <?php
                //форма записи тренировок
                echo $this->partial('set-workout', $this);
                //последние тренировки
                echo $this->partial('workouts', $this);
            ?>
        </div>
        <!-- Вертикальный разделитель --->
        <div id="info-mid">
            <div id="four-vert-line">
                <div id="triple-vert-line"></div>
            </div>
        </div>
        <div id="info-right">
            <?php
            //личные данные
            echo $this->partial('information-card', $this);
            //предстоящие соревнования
            echo $this->partial('sport-events-short', $this);
            //статистика
            echo $this->partial('statistic', $this);

            ?>
        </div>
    </div>
    <?php
        //план тренировок
        echo $this->partial('workout-plan', $this);
    ?>
</div>
<a id="user-id" user-id="<?php echo mysql_real_escape_string($_SESSION['id'])?>"></a>
<?php
    echo $this->partial('footer', $this);
?>